import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { Infer, v } from "convex/values";

// default user roles. can add / remove based on the project as needed
export const ROLES = {
  ADMIN: "admin",
  USER: "user",
  MEMBER: "member",
} as const;

export const roleValidator = v.union(
  v.literal(ROLES.ADMIN),
  v.literal(ROLES.USER),
  v.literal(ROLES.MEMBER),
);
export type Role = Infer<typeof roleValidator>;

const schema = defineSchema(
  {
    // default auth tables using convex auth.
    ...authTables, // do not remove or modify

    // the users table is the default users table that is brought in by the authTables
    users: defineTable({
      name: v.optional(v.string()), // name of the user. do not remove
      image: v.optional(v.string()), // image of the user. do not remove
      email: v.optional(v.string()), // email of the user. do not remove
      emailVerificationTime: v.optional(v.number()), // email verification time. do not remove
      isAnonymous: v.optional(v.boolean()), // is the user anonymous. do not remove

      role: v.optional(roleValidator), // role of the user. do not remove
    }).index("email", ["email"]), // index for the email. do not remove or modify

    // Market data candles stored by symbol
    marketData: defineTable({
      symbol: v.string(),
      candles: v.array(v.object({
        timestamp: v.number(),
        open: v.number(),
        high: v.number(),
        low: v.number(),
        close: v.number(),
        volume: v.number(),
      })),
      updatedAt: v.number(),
    }).index("by_symbol", ["symbol"]),

    // Trade records
    trades: defineTable({
      userId: v.id("users"),
      symbol: v.string(),
      direction: v.union(v.literal("BUY"), v.literal("SELL")),
      entryPrice: v.number(),
      exitPrice: v.optional(v.number()),
      stopLoss: v.number(),
      takeProfit: v.number(),
      quantity: v.number(),
      pnl: v.optional(v.number()),
      pnlPercent: v.optional(v.number()),
      riskReward: v.number(),
      status: v.union(v.literal("OPEN"), v.literal("WIN"), v.literal("LOSS")),
      entryModel: v.optional(v.string()),
      killzone: v.optional(v.string()),
      confluenceScore: v.optional(v.number()),
      screenshot: v.optional(v.string()),
      notes: v.optional(v.string()),
      openedAt: v.number(),
      closedAt: v.optional(v.number()),
    }).index("by_user", ["userId"])
      .index("by_user_status", ["userId", "status"])
      .index("by_user_symbol", ["userId", "symbol"]),

    // Journal entries for trade reflection
    journal: defineTable({
      userId: v.id("users"),
      tradeId: v.optional(v.id("trades")),
      symbol: v.string(),
      title: v.string(),
      content: v.string(),
      tags: v.array(v.string()),
      mood: v.optional(v.union(v.literal("BULLISH"), v.literal("BEARISH"), v.literal("NEUTRAL"), v.literal("FRUSTRATED"), v.literal("CONFIDENT"))),
      lessons: v.optional(v.string()),
      createdAt: v.number(),
      updatedAt: v.number(),
    }).index("by_user", ["userId"])
      .index("by_user_trade", ["userId", "tradeId"]),

    // Strategy signals generated by the combination engine
    signals: defineTable({
      userId: v.id("users"),
      symbol: v.string(),
      direction: v.union(v.literal("BUY"), v.literal("SELL"), v.literal("NEUTRAL")),
      confidence: v.number(),
      confluenceScore: v.number(),
      agreement: v.union(
        v.literal("ELITE"),
        v.literal("INSTITUTIONAL_GRADE"),
        v.literal("HIGH_PROBABILITY"),
        v.literal("MODERATE_PROBABILITY"),
        v.literal("NO_TRADE"),
      ),
      agreementCount: v.number(),
      tradeable: v.boolean(),
      entryZone: v.object({
        high: v.number(),
        low: v.number(),
        midpoint: v.number(),
      }),
      stopLoss: v.number(),
      takeProfit: v.object({
        tp1: v.number(),
        tp2: v.number(),
        tp3: v.number(),
      }),
      riskReward: v.number(),
      killzone: v.string(),
      entryModel: v.string(),
      sessionPriority: v.string(),
      engines: v.array(v.object({
        type: v.string(),
        direction: v.union(v.literal("BUY"), v.literal("SELL"), v.literal("NEUTRAL")),
        confidence: v.number(),
        signal: v.boolean(),
        reason: v.string(),
      })),
      boosters: v.array(v.string()),
      description: v.string(),
      status: v.union(v.literal("ACTIVE"), v.literal("EXPIRED"), v.literal("EXECUTED")),
      createdAt: v.number(),
      expiredAt: v.optional(v.number()),
    }).index("by_user", ["userId"])
      .index("by_user_symbol", ["userId", "symbol"])
      .index("by_user_status", ["userId", "status"]),
  },
  {
    schemaValidation: false,
  },
);

export default schema;
