// ============================================================================
// WARRIKS AI — Strategy Signal Management (Convex)
// CRUD operations for combination engine signals with user isolation
// ============================================================================

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { getCurrentUser } from "./users";

/**
 * Save a new signal generated by the combination engine.
 */
export const createSignal = mutation({
  args: {
    symbol: v.string(),
    direction: v.union(v.literal("BUY"), v.literal("SELL"), v.literal("NEUTRAL")),
    confidence: v.number(),
    confluenceScore: v.number(),
    agreement: v.union(
      v.literal("ELITE"),
      v.literal("INSTITUTIONAL_GRADE"),
      v.literal("HIGH_PROBABILITY"),
      v.literal("MODERATE_PROBABILITY"),
      v.literal("NO_TRADE"),
    ),
    agreementCount: v.number(),
    tradeable: v.boolean(),
    entryZone: v.object({
      high: v.number(),
      low: v.number(),
      midpoint: v.number(),
    }),
    stopLoss: v.number(),
    takeProfit: v.object({
      tp1: v.number(),
      tp2: v.number(),
      tp3: v.number(),
    }),
    riskReward: v.number(),
    killzone: v.string(),
    entryModel: v.string(),
    sessionPriority: v.string(),
    engines: v.array(v.object({
      type: v.string(),
      direction: v.union(v.literal("BUY"), v.literal("SELL"), v.literal("NEUTRAL")),
      confidence: v.number(),
      signal: v.boolean(),
      reason: v.string(),
    })),
    boosters: v.array(v.string()),
    description: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await getCurrentUser(ctx);
    if (!user) throw new Error("Not authenticated");

    const signalId = await ctx.db.insert("signals", {
      userId: user._id,
      symbol: args.symbol,
      direction: args.direction,
      confidence: args.confidence,
      confluenceScore: args.confluenceScore,
      agreement: args.agreement,
      agreementCount: args.agreementCount,
      tradeable: args.tradeable,
      entryZone: args.entryZone,
      stopLoss: args.stopLoss,
      takeProfit: args.takeProfit,
      riskReward: args.riskReward,
      killzone: args.killzone,
      entryModel: args.entryModel,
      sessionPriority: args.sessionPriority,
      engines: args.engines,
      boosters: args.boosters,
      description: args.description,
      status: "ACTIVE",
      createdAt: Date.now(),
    });

    return signalId;
  },
});

/**
 * Mark a signal as EXPIRED (e.g., when a new candle invalidates it).
 */
export const expireSignal = mutation({
  args: {
    signalId: v.id("signals"),
  },
  handler: async (ctx, args) => {
    const user = await getCurrentUser(ctx);
    if (!user) throw new Error("Not authenticated");

    const signal = await ctx.db.get(args.signalId);
    if (!signal || signal.userId !== user._id) throw new Error("Signal not found");

    await ctx.db.patch(args.signalId, {
      status: "EXPIRED",
      expiredAt: Date.now(),
    });
  },
});

/**
 * Mark a signal as EXECUTED (trade was opened based on this signal).
 */
export const executeSignal = mutation({
  args: {
    signalId: v.id("signals"),
  },
  handler: async (ctx, args) => {
    const user = await getCurrentUser(ctx);
    if (!user) throw new Error("Not authenticated");

    const signal = await ctx.db.get(args.signalId);
    if (!signal || signal.userId !== user._id) throw new Error("Signal not found");

    await ctx.db.patch(args.signalId, {
      status: "EXECUTED",
    });
  },
});

/**
 * Get active signals for the current user, optionally filtered by symbol.
 */
export const getActiveSignals = query({
  args: {
    symbol: v.optional(v.string()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const user = await getCurrentUser(ctx);
    if (!user) return [];

    const limit = args.limit ?? 20;

    if (args.symbol) {
      return await ctx.db
        .query("signals")
        .withIndex("by_user_symbol", (q) => q.eq("userId", user._id).eq("symbol", args.symbol!))
        .order("desc")
        .take(limit);
    }

    return await ctx.db
      .query("signals")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .order("desc")
      .take(limit);
  },
});

/**
 * Get signal history (all statuses) for the current user.
 */
export const getSignalHistory = query({
  args: {
    status: v.optional(v.union(v.literal("ACTIVE"), v.literal("EXPIRED"), v.literal("EXECUTED"))),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const user = await getCurrentUser(ctx);
    if (!user) return [];

    const limit = args.limit ?? 50;

    if (args.status) {
      return await ctx.db
        .query("signals")
        .withIndex("by_user_status", (q) => q.eq("userId", user._id).eq("status", args.status!))
        .order("desc")
        .take(limit);
    }

    return await ctx.db
      .query("signals")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .order("desc")
      .take(50);
  },
});
